bugfix: Fix crash when pos_encoding_mode is passed as int (#1413)
This PR is to fix this issue caused by
https://github.com/flashinfer-ai/flashinfer/commit/85d75ca915e64f664dfc33ea5f52446d279bc2ad
```  
File "/scratch/repo/flashinfer/flashinfer/prefill.py", line 83, in get_fmha_module                                                                                                               pos_encoding_mode.value,                                                                                                                                                                       ^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                    AttributeError: 'int' object has no attribute 'value' 
```

Update get_fmha_module to expect pos_encoding_mode as an Enum instead of
an int; raises error otherwise.

cc @yzh119