perf: Fix silent bug with FP8 per tensor non-gated MoE (#2882)
<!-- .github/pull_request_template.md -->

## 📌 Description

This PR fixed a **silent bug** that forces fallback tactic with _TRTLLM
MoE FP8 and non-gated models_ (Nemotron).
```
[Autotuner]: Failed to get valid tactics for ... Error occurred: FP8 per-tensor currently supports gated activations only, got act_type=6
```

There is no crash, only a performance bug (fallback tactic will always
be selected).

The error raised from the C++ code seems to be hidden by this try-except
in function `get_trtllm_moe_sm100_module`:

https://github.com/flashinfer-ai/flashinfer/blob/main/flashinfer/fused_moe/core.py#L924

Code:
```python
            if instance_key not in MoERunner.valid_tactics_dict:
                try:
                    valid_tactics = moe_op.trtllm_get_valid_moe_configs(*instance_key)
                except Exception as e:
                    logger.debug(
                        f"[Autotuner]: Failed to get valid tactics for {instance_key}. Error occurred: {e}"
                    )
                    return []
                MoERunner.valid_tactics_dict[instance_key] = valid_tactics
            return MoERunner.valid_tactics_dict[instance_key]
```

Only by enabling `FLASHINFER_LOGGING_LEVEL=DEBUG` the error appears
(`logger.debug`).

This bug does not exist in flashinfer version 0.6.6.

### With version 0.6.6

commit `70b142b75b46aa56e7f675a8e6ec1a977352c91f`

```bash
# from flashinfer clone path
git checkout v0.6.6

uv pip install -v .

flashinfer clear-cache

export FLASHINFER_LOGGING_LEVEL=DEBUG

python -m pytest --maxfail 1 -sv --tb short \
tests/moe/test_trtllm_gen_fused_moe.py::test_deepseekv3_routing  \
-k "Relu2 and nemotron_3_dummy and FP8_PerTensor"

```

Output:
```
tests/moe/test_trtllm_gen_fused_moe.py::test_deepseekv3_routing[Relu2-Shuffled_MajorK-nemotron_3_dummy-FP8_PerTensor-2944-1024-8] 2026-03-24 12:42:51,264 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
2026-03-24 12:42:51,265 - DEBUG - cubin_loader.py:182 - flashinfer.jit: Loading from /root/.cache/flashinfer/cubins/b55211623be7f5697c5262ffd8361fc06c147bc9/batched_gemm-b3c1646-c111d7c/checksums.txt
2026-03-24 12:42:51,266 - DEBUG - cubin_loader.py:182 - flashinfer.jit: Loading from /root/.cache/flashinfer/cubins/b55211623be7f5697c5262ffd8361fc06c147bc9/batched_gemm-b3c1646-c111d7c/include/flashinferMetaInfo.h
2026-03-24 12:42:51,270 - DEBUG - cubin_loader.py:182 - flashinfer.jit: Loading from /root/.cache/flashinfer/cubins/flashinfer/trtllm/batched_gemm/trtllmGen_bmm_export/BatchedGemmEnums.h
2026-03-24 12:42:51,271 - DEBUG - cubin_loader.py:182 - flashinfer.jit: Loading from /root/.cache/flashinfer/cubins/flashinfer/trtllm/batched_gemm/trtllmGen_bmm_export/BatchedGemmInterface.h
...
2026-03-24 12:59:50,604 - DEBUG - autotuner.py:750 - flashinfer.jit: [Autotuner]: generated profile: OptimizationProfile(shapes=[[DynamicDim(min=1, opt=1, max=2), StaticDim(val=1024)], [DynamicDim(min=1, opt=1, max=2), StaticDim(val=512)], [DynamicDim(min=1, opt=1, max=2), StaticDim(val=22)], [DynamicDim(min=1, opt=1, max=2), StaticDim(val=22)], [DynamicDim(min=1, opt=1, max=2), StaticDim(val=1024)]], tensor_initializers=[<function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155d260>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155eb60>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155ed40>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155d120>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155ea20>])
2026-03-24 12:59:50,604 - DEBUG - autotuner.py:750 - flashinfer.jit: [Autotuner]: generated profile: OptimizationProfile(shapes=[[DynamicDim(min=2, opt=2, max=4), StaticDim(val=1024)], [DynamicDim(min=2, opt=2, max=4), StaticDim(val=512)], [DynamicDim(min=2, opt=2, max=4), StaticDim(val=22)], [DynamicDim(min=2, opt=2, max=4), StaticDim(val=22)], [DynamicDim(min=2, opt=2, max=4), StaticDim(val=1024)]], tensor_initializers=[<function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155d260>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155eb60>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155ed40>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155d120>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155ea20>])
2026-03-24 12:59:50,604 - DEBUG - autotuner.py:750 - flashinfer.jit: [Autotuner]: generated profile: OptimizationProfile(shapes=[[DynamicDim(min=4, opt=4, max=8), StaticDim(val=1024)], [DynamicDim(min=4, opt=4, max=8), StaticDim(val=512)], [DynamicDim(min=4, opt=4, max=8), StaticDim(val=22)], [DynamicDim(min=4, opt=4, max=8), StaticDim(val=22)], [DynamicDim(min=4, opt=4, max=8), StaticDim(val=1024)]], tensor_initializers=[<function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155d260>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155eb60>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155ed40>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155d120>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155ea20>])
...
2026-03-24 13:00:09,444 - DEBUG - autotuner.py:750 - flashinfer.jit: [Autotuner]: generated profile: OptimizationProfile(shapes=[[DynamicDim(min=2048, opt=2048, max=4096), StaticDim(val=1024)], [DynamicDim(min=2048, opt=2048, max=4096), StaticDim(val=512)], [DynamicDim(min=2048, opt=2048, max=4096), StaticDim(val=22)], [DynamicDim(min=2048, opt=2048, max=4096), StaticDim(val=22)], [DynamicDim(min=2048, opt=2048, max=4096), StaticDim(val=1024)]], tensor_initializers=[<function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155d260>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155eb60>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155ed40>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155d120>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155ea20>])
2026-03-24 13:00:09,444 - DEBUG - autotuner.py:750 - flashinfer.jit: [Autotuner]: generated profile: OptimizationProfile(shapes=[[DynamicDim(min=4096, opt=4096, max=inf), StaticDim(val=1024)], [DynamicDim(min=4096, opt=4096, max=inf), StaticDim(val=512)], [DynamicDim(min=4096, opt=4096, max=inf), StaticDim(val=22)], [DynamicDim(min=4096, opt=4096, max=inf), StaticDim(val=22)], [DynamicDim(min=4096, opt=4096, max=inf), StaticDim(val=1024)]], tensor_initializers=[<function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155d260>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155eb60>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155ed40>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155d120>, <function get_trtllm_moe_sm100_module.<locals>.MoERunner.<lambda> at 0xfffbd155ea20>])
2026-03-24 13:00:09,445 - INFO - autotuner.py:268 - flashinfer.jit: [Autotuner]: Autotuning process ends
PASSED
...
==================================================================================== 3 passed, 51 skipped, 6426 deselected in 1043.61s (0:17:23) =====================================================================================
```

### With main branch

commit `b8931925fbda0b4a77a79ac4b6577a1da235f605` (currently tagged as
`v0.6.7`)

```bash
# from flashinfer clone path
git checkout v0.6.7

uv pip install -v .

flashinfer clear-cache

export FLASHINFER_LOGGING_LEVEL=DEBUG

python -m pytest --maxfail 1 -sv --tb short \
tests/moe/test_trtllm_gen_fused_moe.py::test_deepseekv3_routing  \
-k "Relu2 and nemotron_3_dummy and FP8_PerTensor"
```

Output:
```
tests/moe/test_trtllm_gen_fused_moe.py::test_deepseekv3_routing[Relu2-Shuffled_MajorK-nemotron_3_dummy-FP8_PerTensor-2944-1024-8] 2026-03-24 12:28:10,611 - INFO - autotuner.py:446 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
...
Traceback (most recent call last):
  File "<unknown>", line 0, in __tvm_ffi_trtllm_get_valid_moe_configs
  File "/opt/flashinfer/flashinfer/data/csrc/trtllm_fused_moe_kernel_launcher.cu", line 2234, in tvm::ffi::Array<tvm::ffi::Array<long int> > flashinfer::trtllm_get_valid_moe_configs(int64_t, int64_t, Fp8QuantizationType, int64_t, int64_t, int64_t, int64_t, int64_t, bool, int64_t, int64_t)
NotImplementedError: FP8 per-tensor currently supports gated activations only, got act_type=6.
2026-03-24 12:36:01,582 - DEBUG - core.py:925 - flashinfer.jit: [Autotuner]: Failed to get valid tactics for (<DtypeTrtllmGen.E4m3: 1050629>, <DtypeTrtllmGen.E4m3: 1050629>, <Fp8QuantizationType.NoneFp8: 0>, 22, 1024, 2944, 512, <ActivationType.Relu2: 6>, True, <WeightLayout.MajorK: 0>, 1). Error occurred: FP8 per-tensor currently supports gated activations only, got act_type=6.
Traceback (most recent call last):
  File "<unknown>", line 0, in __tvm_ffi_trtllm_get_valid_moe_configs
  File "/opt/flashinfer/flashinfer/data/csrc/trtllm_fused_moe_kernel_launcher.cu", line 2234, in tvm::ffi::Array<tvm::ffi::Array<long int> > flashinfer::trtllm_get_valid_moe_configs(int64_t, int64_t, Fp8QuantizationType, int64_t, int64_t, int64_t, int64_t, int64_t, bool, int64_t, int64_t)
NotImplementedError: FP8 per-tensor currently supports gated activations only, got act_type=6.
2026-03-24 12:36:01,583 - DEBUG - core.py:925 - flashinfer.jit: [Autotuner]: Failed to get valid tactics for (<DtypeTrtllmGen.E4m3: 1050629>, <DtypeTrtllmGen.E4m3: 1050629>, <Fp8QuantizationType.NoneFp8: 0>, 22, 1024, 2944, 512, <ActivationType.Relu2: 6>, True, <WeightLayout.MajorK: 0>, 2). Error occurred: FP8 per-tensor currently supports gated activations only, got act_type=6.
...
Traceback (most recent call last):
  File "<unknown>", line 0, in __tvm_ffi_trtllm_get_valid_moe_configs
  File "/opt/flashinfer/flashinfer/data/csrc/trtllm_fused_moe_kernel_launcher.cu", line 2234, in tvm::ffi::Array<tvm::ffi::Array<long int> > flashinfer::trtllm_get_valid_moe_configs(int64_t, int64_t, Fp8QuantizationType, int64_t, int64_t, int64_t, int64_t, int64_t, bool, int64_t, int64_t)
NotImplementedError: FP8 per-tensor currently supports gated activations only, got act_type=6.
2026-03-24 12:36:15,119 - DEBUG - core.py:925 - flashinfer.jit: [Autotuner]: Failed to get valid tactics for (<DtypeTrtllmGen.E4m3: 1050629>, <DtypeTrtllmGen.E4m3: 1050629>, <Fp8QuantizationType.NoneFp8: 0>, 22, 1024, 2944, 512, <ActivationType.Relu2: 6>, True, <WeightLayout.MajorK: 0>, 512). Error occurred: FP8 per-tensor currently supports gated activations only, got act_type=6.
Traceback (most recent call last):
  File "<unknown>", line 0, in __tvm_ffi_trtllm_get_valid_moe_configs
  File "/opt/flashinfer/flashinfer/data/csrc/trtllm_fused_moe_kernel_launcher.cu", line 2234, in tvm::ffi::Array<tvm::ffi::Array<long int> > flashinfer::trtllm_get_valid_moe_configs(int64_t, int64_t, Fp8QuantizationType, int64_t, int64_t, int64_t, int64_t, int64_t, bool, int64_t, int64_t)
NotImplementedError: FP8 per-tensor currently supports gated activations only, got act_type=6.
2026-03-24 12:36:15,119 - DEBUG - core.py:925 - flashinfer.jit: [Autotuner]: Failed to get valid tactics for (<DtypeTrtllmGen.E4m3: 1050629>, <DtypeTrtllmGen.E4m3: 1050629>, <Fp8QuantizationType.NoneFp8: 0>, 22, 1024, 2944, 512, <ActivationType.Relu2: 6>, True, <WeightLayout.MajorK: 0>, 1024). Error occurred: FP8 per-tensor currently supports gated activations only, got act_type=6.
Traceback (most recent call last):
  File "<unknown>", line 0, in __tvm_ffi_trtllm_get_valid_moe_configs
  File "/opt/flashinfer/flashinfer/data/csrc/trtllm_fused_moe_kernel_launcher.cu", line 2234, in tvm::ffi::Array<tvm::ffi::Array<long int> > flashinfer::trtllm_get_valid_moe_configs(int64_t, int64_t, Fp8QuantizationType, int64_t, int64_t, int64_t, int64_t, int64_t, bool, int64_t, int64_t)
NotImplementedError: FP8 per-tensor currently supports gated activations only, got act_type=6.
2026-03-24 12:36:15,119 - DEBUG - core.py:925 - flashinfer.jit: [Autotuner]: Failed to get valid tactics for (<DtypeTrtllmGen.E4m3: 1050629>, <DtypeTrtllmGen.E4m3: 1050629>, <Fp8QuantizationType.NoneFp8: 0>, 22, 1024, 2944, 512, <ActivationType.Relu2: 6>, True, <WeightLayout.MajorK: 0>, 2048). Error occurred: FP8 per-tensor currently supports gated activations only, got act_type=6.
Traceback (most recent call last):
  File "<unknown>", line 0, in __tvm_ffi_trtllm_get_valid_moe_configs
  File "/opt/flashinfer/flashinfer/data/csrc/trtllm_fused_moe_kernel_launcher.cu", line 2234, in tvm::ffi::Array<tvm::ffi::Array<long int> > flashinfer::trtllm_get_valid_moe_configs(int64_t, int64_t, Fp8QuantizationType, int64_t, int64_t, int64_t, int64_t, int64_t, bool, int64_t, int64_t)
NotImplementedError: FP8 per-tensor currently supports gated activations only, got act_type=6.
2026-03-24 12:36:15,120 - DEBUG - core.py:925 - flashinfer.jit: [Autotuner]: Failed to get valid tactics for (<DtypeTrtllmGen.E4m3: 1050629>, <DtypeTrtllmGen.E4m3: 1050629>, <Fp8QuantizationType.NoneFp8: 0>, 22, 1024, 2944, 512, <ActivationType.Relu2: 6>, True, <WeightLayout.MajorK: 0>, 4096). Error occurred: FP8 per-tensor currently supports gated activations only, got act_type=6.
2026-03-24 12:36:15,137 - DEBUG - cubin_loader.py:182 - flashinfer.jit: Loading from /root/.cache/flashinfer/cubins/b55211623be7f5697c5262ffd8361fc06c147bc9/batched_gemm-b3c1646-c111d7c/Bmm_E4m3_E4m3E4m3_Fp32_t128x64x256u2_s5_et128x64_m256x64x32_cga2x1x1_16dp256b_rM_TN_transOut_tokSfB_schPd2x1x2x3_relu2_bN_tma_tmaSf_rgTma_clmp_lbW8_dynB_sm100f.cubin
2026-03-24 12:36:15,138 - DEBUG - cubin_loader.py:182 - flashinfer.jit: Loading from /root/.cache/flashinfer/cubins/b55211623be7f5697c5262ffd8361fc06c147bc9/batched_gemm-b3c1646-c111d7c/Bmm_Bfloat16_E4m3E4m3_Fp32_t128x64x128_s8_et128x64_m256x64x32_cga2x1x1_16dp256b_rM_TN_transOut_schPd2x1x2x3_bN_rgTma_clmp_dynB_sm100f.cubin
2026-03-24 12:36:15,138 - INFO - autotuner.py:455 - flashinfer.jit: [Autotuner]: Autotuning process ends
PASSED
...
===================================================================================== 3 passed, 51 skipped, 6426 deselected in 489.92s (0:08:09) =====================================================================================
```

In this case we can see the error I removed:
`2026-03-24 12:36:01,582 - DEBUG - core.py:925 - flashinfer.jit:
[Autotuner]: Failed to get valid tactics for ... Error occurred: FP8
per-tensor currently supports gated activations only, got act_type=6.`

But the test does not fail.

With this fix we are back to behavior of 0.6.6 (no `Failed to get valid
tactics for`).

Notes:
All of the above tested using GB200 GPU.
The artifacts path for TRTLLM_GEN_BMM did not change between 0.6.6 and
0.6.7:
`b55211623be7f5697c5262ffd8361fc06c147bc9`.

<!-- What does this PR do? Briefly describe the changes and why they’re
needed. -->

## 🔍 Related Issues

<!-- Link any related issues here -->

## 🚀 Pull Request Checklist

Thank you for contributing to FlashInfer! Before we review your pull
request, please make sure the following items are complete.

### ✅ Pre-commit Checks

- [x] I have installed `pre-commit` by running `pip install pre-commit`
(or used your preferred method).
- [x] I have installed the hooks with `pre-commit install`.
- [x] I have run the hooks manually with `pre-commit run --all-files`
and fixed any reported issues.

> If you are unsure about how to set up `pre-commit`, see [the
pre-commit documentation](https://pre-commit.com/).

## 🧪 Tests

- [x] Tests have been added or updated as needed.
- [x] All tests are passing (`unittest`, etc.).

## Reviewer Notes

<!-- Optional: anything you'd like reviewers to focus on, concerns, etc.
-->


<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->

## Summary by CodeRabbit

* **Bug Fixes**
* Expanded FP8 quantization support to work with a broader range of
activation types, removing an overly restrictive validation constraint.

<!-- end of auto-generated comment: release notes by coderabbit.ai -->