bugfix: Cast build paths to str before setuputils Extension
Before, when building wheel with AOT enabled:
```
...
    return _build_backend().build_wheel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/setuptools/build_meta.py", line 415, in build_wheel
    return self._build_with_temp_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
    self.run_setup()
  File "/usr/local/lib/python3.12/dist-packages/setuptools/build_meta.py", line 313, in run_setup
    exec(code, locals())
  File "<string>", line 275, in <module>
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/cpp_extension.py", line 1207, in CUDAExtension
    return setuptools.Extension(name, sources, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/setuptools/extension.py", line 133, in __init__
    super().__init__(name, sources, *args, **kw)
  File "/usr/local/lib/python3.12/dist-packages/setuptools/_distutils/extension.py", line 111, in __init__
    raise AssertionError("'sources' must be a list of strings")
AssertionError: 'sources' must be a list of strings
...
```
Due to `setuptools/_distutils/extension.py`:
```
...
        if not isinstance(name, str):
            raise AssertionError("'name' must be a string")
        if not (isinstance(sources, list) and all(isinstance(v, str) for v in sources)):
            raise AssertionError("'sources' must be a list of strings")
...
```