bugfix: Fix building without `get_requires*()` invocation (#1226)
<!-- .github/pull_request_template.md -->

## 📌 Description

Add the remaining PEP 517 build hooks explicitly, and ensure that they
perform the required setup, in order to fix building when the build
backend does not query the build dependencies. For example, this can
happen when using:

```
$ python -m build -wn --skip-de
* Building wheel...
running bdist_wheel
[...]
error: package directory 'build/aot-ops-package-dir' does not exist

ERROR Backend subprocess exited when trying to invoke build_wheel
```

Since PEP 517 does not require calling `get_requires*()` hook, and the
build backend can invoke `build_*()` immediately instead, override it as
well.


## 🔍 Related Issues

<!-- Link any related issues here -->

## 🚀 Pull Request Checklist

Thank you for contributing to FlashInfer! Before we review your pull
request, please make sure the following items are complete.

### ✅ Pre-commit Checks

- [x] I have installed `pre-commit` by running `pip install pre-commit`
(or used your preferred method).
- [x] I have installed the hooks with `pre-commit install`.
- [x] I have run the hooks manually with `pre-commit run --all-files`
and fixed any reported issues.

> If you are unsure about how to set up `pre-commit`, see [the
pre-commit documentation](https://pre-commit.com/).

## 🧪 Tests

- [ ] Tests have been added or updated as needed.
- [ ] All tests are passing (`unittest`, etc.).

## Reviewer Notes

<!-- Optional: anything you'd like reviewers to focus on, concerns, etc.
-->
Unclear if I'm supposed to check test-related checkboxes if I'm not
touching any installed code.